ZSH=~/.config/zsh

for file in $ZSH/lib/*;
do
    source $file
done

for plugin in $ZSH/plugins/*;
do
    source $plugin
done

source $ZSH/prompt.zsh
source $ZSH/aliases.zsh
source $ZSH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

complete -F _complete_alias dots
complete -F _complete_alias ls
