foreground              #FFFFFF
background              #191530
selection_foreground    #191530
selection_background    #FFFFFF
cursor                  #E2E7EE
cursor_text_color       #040404

active_tab_foreground     #191530
active_tab_background     #6B6392
inactive_tab_foreground   #6B6392
inactive_tab_background   #191530

# black
color0      #2F2952
color8      #5F578F

# red
color1      #CCE1FF
color9      #AAC7F0

# green
color2      #CCD7FF
color10     #AAB9F0

# yellow
color3      #D5CCFF
color11     #B6AAF0

# blue
color4      #A59AE6
color12     #A59AE6

# magenta
color5      #9AAAE6
color13     #9AAAE6

# cyan
color6      #A79AE6
color14     #A79AE6

# white
color7      #CCE1FF
color15     #AAC7F0
