foreground              #FFFFFF
background              #1F1A23
selection_foreground    #1F1A23
selection_background    #FFFFFF
cursor                  #C39972
cursor_text_color       #0F1011

active_tab_foreground     #1F1A23
active_tab_background     #935E46
inactive_tab_foreground   #935E46
inactive_tab_background   #1F1A23

# black
color0      #3F2952
color8      #76578F

# red
color1      #FFE5CC
color9      #F0CCAA

# green
color2      #FFCCCF
color10     #F0AAAE

# yellow
color3      #FFDCCC
color11     #F0C0AA

# blue
color4      #C49AE6
color12     #C49AE6

# magenta
color5      #E69A9E
color13     #E69A9E

# cyan
color6      #E6B19A
color14     #E6B19A

# white
color7      #FFE5CC
color15     #F0CCAA
