foreground              #FFFFFF
background              #120809
selection_foreground    #120809
selection_background    #FFFFFF
cursor                  #961520
cursor_text_color       #FFFFFF

active_tab_foreground     #120809
active_tab_background     #873B3B
inactive_tab_foreground   #873B3B
inactive_tab_background   #120809

# black
color0      #52292D
color8      #8F575D

# red
color1      #FFCCD0
color9      #F0AAB0

# green
color2      #FFCCCE
color10     #F0AAAE

# yellow
color3      #FFCCCC
color11     #F0AAAA

# blue
color4      #E69AA1
color12     #E69AA1

# magenta
color5      #E69A9D
color13     #E69A9D

# cyan
color6      #E69A9A
color14     #E69A9A

# white
color7      #FFCCD0
color15     #F0AAB0
