NextEpisodePrompt=false
ImagePreview=true
Provider=allanime
PercentageToMarkComplete=85
AddMissingOptions=true
DiscordPresence=true
MpvArgs=[]
SaveMpvSpeed=true
SkipOp=true
Player=mpv
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,CONTINUE_LAST
SkipRecap=true
SkipEd=true
SubsLanguage=english
StoragePath=$HOME/.local/share/curd
AnimeNameLanguage=english
AlternateScreen=true
SubOrDub=sub
RofiSelection=true
DiscordClientId=1287457464148820089
ScoreOnCompletion=true
SkipFiller=true
