#!/bin/bash

swww init
if [[ $# -lt 1 ]] || [[ ! -d $1   ]]; then
	echo "Usage:
	$0 <dir containing images>"
	exit 1
fi

while true;
do
  img=$(find "$1" -type f | shuf -n1)
  swww img "$img" --transition-type=wipe --transition-angle=30 --transition-step=90
  sleep 1800
done
