-- Generated by nwg-displays on 2026-05-19 at 22:19:32. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.21",
    position = "0x0",
    scale = 1.33
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1440x0",
    scale = 1.0,
    mirror = "eDP-1"
})
