
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    # kb_layout = us
    # follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat 
    # numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = true
    }

}



# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}

env = PATH,$HOME/.cargo/bin:$PATH
exec-once = snappy-switcher --daemon

layerrule = animation slide right, match:namespace swaync-control-center
layerrule = blur true,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi
layerrule = blur true,match:namespace notifications
layerrule = ignore_alpha 0,match:namespace notifications
layerrule = blur true,match:namespace swaync-notification-window
layerrule = ignore_alpha 0,match:namespace swaync-notification-window
layerrule = blur true,match:namespace swaync-control-center
layerrule = ignore_alpha 0,match:namespace swaync-control-center
layerrule = blur true,match:namespace logout_dialog


# Keybindings
bind = ALT, Tab, exec, snappy-switcher next
bind = ALT SHIFT, Tab, exec, snappy-switcher prev

bind = SUPER, N, exec, swaync-client -t
bind = SUPER SHIFT, N, exec, epaper
bind = SUPER, A, exec, curd
bind = SUPER, W, exec, watch_streams
bind = SUPER, R, exec, f1
